# all configuration options
# https://github.com/alacritty/alacritty/blob/master/alacritty.yml

window:
  dynamic_padding: true
  # remove title bar
  # https://github.com/alacritty/alacritty/issues/168
  decorations: none
  padding:
    x: 3
    y: 3

# Live config reload (changes require restart)
live_config_reload: true
hide_cursor_when_typing: false
cursor:
  unfocused_hollow: false

font:
  size: 14
  normal:
    family: Hack
    style: Regular

# Colors (Snazzy)
# https://github.com/alebelcor/alacritty-snazzy/blob/master/snazzy.yml
draw_bold_text_with_bright_colors: true

colors:

  primary:
    background: '#282a36'
    foreground: '#eff0eb'

  cursor:
    cursor: '#97979b'

  selection:
    text:       '#282a36'
    background: '#feffff'

  normal:
    black:   '#282a36'
    red:     '#ff5c57'
    green:   '#5af78e'
    yellow:  '#f3f99d'
    blue:    '#57c7ff'
    magenta: '#ff6ac1'
    cyan:    '#9aedfe'
    white:   '#f1f1f0'

  bright:
    black:   '#686868'
    red:     '#ff5c57'
    green:   '#5af78e'
    yellow:  '#f3f99d'
    blue:    '#57c7ff'
    magenta: '#ff6ac1'
    cyan:    '#9aedfe'
    white:   '#eff0eb'
